let xlsx = require("json-as-xlsx")

let data = [
  {
    sheet: "INWARD",
    columns: [
      { label: "Issue Type", value: "type_of_issue" },
      { label: "Priority", value: "priority" },
      // { label: "Phone", value: (row) => (row.more ? row.more.phone || "" : "") }, 
    ],
    // content: [
    //   { user: "Rupesh", age: 20, more: { phone: "11111,111" } },
    //   { user: "Kumar", age: 21, more: { phone: "12345678" } },
    // ],

    content:[
      { type_of_issue: 'Hardware', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Low' },
      { type_of_issue: 'Software', priority: 'Low' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Urgent' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Hardware', priority: 'Normal' },
      { type_of_issue: 'Other', priority: '' },
      { type_of_issue: 'New Requirement', priority: 'Normal' },
      { type_of_issue: 'Connectivity', priority: 'Normal' },
      { type_of_issue: 'Allocation', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Low' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Server', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Urgent' },
      { type_of_issue: 'Other', priority: 'Low' },
      { type_of_issue: 'Hardware', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Hardware', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Urgent' },
      { type_of_issue: 'Hardware', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Software', priority: '' },
      { type_of_issue: 'Software', priority: 'Normal' },
      { type_of_issue: 'Other', priority: 'Normal' },
      { type_of_issue: 'Hardware', priority: 'Urgent' },
      { type_of_issue: 'Software', priority: 'Urgent' },
    ],
  },
  {
    sheet: "OUTWARD",
    columns: [
      { label: "User", value: "user" }, 
      { label: "Age", value: "age", format: '# "years"' },
      { label: "Phone", value: "more.phone", format: "(###) ###-####" }, 
    ],
    content: [
      { user: "Manuel", age: 16, more: { phone: 9999999900 } },
      { user: "Ana", age: 17, more: { phone: 8765432135 } },
    ],
  },
]

let settings = {
  fileName: "ExcelData",
  extraLength: 3, 
  writeMode: "writeFile", 
  writeOptions: {}, 
  RTL: false, 
}

// module.exports={data,settings}

xlsx(data, settings)